name: "branch deploy demo"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write 
  deployments: write
  packages: write
  contents: write 
  checks: read 
  statuses: read

jobs:
    deploy:
        if: ${{ github.event.issue.pull_request }}
        environment: QA
        runs-on: ubuntu-latest
        steps:
            - uses: github/branch-deploy@v10.4.1
              id: branch-deploy
              with:
                trigger: ".deploy"
                environment: QA
            - uses: actions/checkout@v4
            - name: Install Salesforce CLI
              run: npm install -g @salesforce/cli@latest
            - name: fake regular deploy
              if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
              run: echo "I am doing a fake regular deploy"
