name: "branch deploy demo"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write 
  deployments: write
  packages: write
  contents: write 
  checks: read 
  statuses: read

jobs:
    deploy:
        if: ${{ github.event.issue.pull_request }}
        runs-on: ubuntu-latest
        steps:
            - uses: github/branch-deploy@v10.4.1
              id: branch-deploy
              with:
                trigger: ".deploy"
                environment_targets: QA,UAT
            - uses: actions/checkout@v4
              with:
                ref: ${{ steps.branch-deploy.outputs.sha }}
                fetch-depth: 0
            - name: Install Salesforce CLI
              run: npm install -g @salesforce/cli@latest
            - name: Populate salesforce credentials
              run: |
                echo $SF_AUTH_JSON > authFile.json
              env:
                SF_AUTH_JSON: ${{ secrets.SF_AUTH_JSON }}
            - name: Salesforce authentication
              run: |
                sf org login sfdx-url --sfdx-url-file authFile.json
            - name: Get Delta
              run: |
                echo y | sfdx plugins:install sfdx-git-delta
                sf sgd source delta --to "HEAD" --from "origin/main" --output-dir "."
                cat package/package.xml
                ls
            - name: fake regular deploy
              if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
              run: echo "I am doing a fake regular deploy"
    issue-comment:
        if: ${{ github.event.issue.comments && !github.event.issue.pull_request }}
        environment: QA
        runs-on: ubuntu-latest
        steps:
            - uses: github/branch-deploy@v10.4.1
              id: branch-deploy
              with:
                trigger: ".deploy"
                environment: QA
            - uses: actions/checkout@v4
            - name: Install Salesforce CLI
              run: npm install -g @salesforce/cli@latest
            - name: Populate salesforce credentials
              run: |
                echo $SF_AUTH_JSON > authFile.json
              env:
                SF_AUTH_JSON: ${{ secrets.SF_AUTH_JSON }}
            - name: Salesforce authentication
              run: |
                sf org login sfdx-url --sfdx-url-file authFile.json
            - name: fake regular deploy
              if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
              run: echo "I am doing a fake regular deploy"
    
